baseURL = "https://rbharadwaj9.github.io"

# set your your own ga token here.
googleAnalytics = ""

languageCode = "en-us"

# for using avicenna you need to set the themes to 'avicenna'
enableEmoji = true
theme = "maverick"

# This is your page title, it appears in your tab
title = "Rajiv Bharadwaj"

# number of posts to show on the blog page
[pagination]
    pagerSize = 10

[markup]
  [markup.goldmark.renderer]
    unsafe = true
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[params]
  # https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShaggyMullet&accessoriesType=Prescription02&hairColor=Black&facialHairType=Blank&clotheType=Hoodie&clotheColor=Black&eyeType=Default&eyebrowType=Default&mouthType=Twinkle&skinColor=Brown
  logo = "images/favicon.ico"
  description = "Rajiv's Personal Website"
  name = "Rajiv Bharadwaj"

[params.footer]
    text = """
    Theme based on Maverick by Calvin Canh Tran ([@canhtran](https://github.com/canhtran))
    """

[params.news]
    numNews = 5

[permalinks]
  pages = "/:slug"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = "-110"
  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/posts/"
    weight = -200

[taxonomies]
  tag = "tags"

