baseURL = "https://rbharadwaj9.github.io"


languageCode = "en-us"

enableEmoji = true
theme = "maverick"

# This is your page title, it appears in your tab
title = "Rajiv Bharadwaj"

# number of posts to show on the blog page
[pagination]
    pagerSize = 10

[markup]
  [markup.goldmark.renderer]
    unsafe = true
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[params]
  # https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShaggyMullet&accessoriesType=Prescription02&hairColor=Black&facialHairType=Blank&clotheType=Hoodie&clotheColor=Black&eyeType=Default&eyebrowType=Default&mouthType=Twinkle&skinColor=Brown
  logo = "images/favicon.ico"
  description = "Rajiv's Personal Website"
  name = "Rajiv Bharadwaj"

[params.footer]
    text = """
    Theme based on Maverick by Calvin Canh Tran ([@canhtran](https://github.com/canhtran))
    """

[params.umami]
    scriptUrl = "https://cloud.umami.is/script.js"
    websiteId = "02d17b58-2365-40d2-bad6-68bfa9f738b6"

[params.news]
    numNews = 5

[permalinks]
  pages = "/:slug"

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "#projects-section"
    weight = -110
  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "#news-section"
    weight = -200

[taxonomies]
  tag = "tags"

